### ISSUE TITLE
Porting over sidekiq support

### ISSUE THREAD

**Issue by rubendinho** [cpoms/innkeeper#1]
I'm not sure what the best approach would be to handle `Sidekiq` support for `Innkeeper`, but happy to help with this. 

@mikecmpbll: I am happy to clone the latest version of `apartment-sidekiq` gem, rename to `innkeeper-sidekiq` and open a PR to your fork of `apartment-sidekiq`, but wanted to see if perhaps there's a better approach to avoid 100% duplication of the underlying code. Obviously `innkeeper` is a significant re-write of Apartment, but in the case of `apartment-sidekiq`, the code would remain identical.

**Comment by rubendinho** [comment]
Looking at the `apartment-sidekiq` code, perhaps a more elegant approach would be to add sidekiq  support directly into this gem as a configuration option: 

`config.sidekiq = true`
OR
`config.background_job_adapter = :sidekiq`

I'm not 100% sure how to properly implement this, but would be glad to take a stab with some guidance/advice.

**Comment by mikecmpbll** [comment]
hey @rubendinho. that sounds great. i think cloning is probably the easiest approach at the moment :+1:

**Comment by rubendinho** [comment]
Just opened a PR at: https://github.com/cpoms/apartment-sidekiq/pull/1

**Comment by nadrooJ** [comment]
Ported [here](https://github.com/cpoms/innkeeper-sidekiq)
