### ISSUE TITLE
Bugfixes / enhancements from Apartment 2.2

### ISSUE THREAD

**Issue by rubendinho** [cpoms/innkeeper#3]
I keep running into certain issues that look like they might have been resolved in the current Apartment repo since this codebase was originally forked from the Apartment repo. 

I have tried patching them as I run into them, but was wondering if there are any plans to do some kind of a "rebase" against the current Apartment repo.  I know there were quite a few issues in the other repo that this repo probably addresses and vice versa, so perhaps there's a way to let people know about the existence of this project. 

On a related note, are there some obvious incompatibilities with Rails 6 here? I'm running into some weird problems (for example, data is being silently "lost" - it looks like it saves in the console but actually is not saved at all).  Finding it quite challenging to troubleshoot.

**Comment by mikecmpbll** [comment]
i think we'll look at them one by one as these repos have diverged so significantly that a kind of rebase would likely be nigh-on impossible. feel free to create an issue/PR for any that you spot and we should be able to crack it nice and quickly :)
